### ISSUE TITLE
请问您就是Pal4DBBrowser的作者么?

### ISSUE THREAD

**Issue by elGilberto** [pumsscco/pal4#1]
我通过Google搜索关键词发现这个页面的。疫情期间有空玩仙剑4时用到了您开发的数据库浏览器，再依照软件里的表格对游戏文件进行编辑，很感谢您开发的这个软件啊。另外，从这个项目来看请问您最近在研究仙剑4数据库的信息吧？

**Comment by pumsscco** [comment]
不是，我是受Pal4DBBrowser启发，用winhex自己研究的，2016年研究的，python2.7版，这是golang重写的版本
